apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  type: LoadBalancer  # Tipo do Service
  selector:  # Seleciona os Pods que serão expostos pelo Service
    app: nginx  # Nesse caso, os Pods com o label app=nginx
  ports:
  - protocol: TCP
    port: 80  # Porta do Service, que será mapeada para a porta 8080 do Pod
    targetPort: 8080  # porta dos Pods