apiVersion: apps/v1
kind: StatefulSet  # Tipo do recurso que estamos criando, no caso um StatefulSet
metadata:
  name: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  serviceName: "nginx"
  replicas: 3
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
          name: http
        volumeMounts:
        - name: www
          mountPath: /usr/share/nginx/html
  volumeClaimTemplates:  # Como estamos utilizando StatefulSet, precisamos criar um template de volume para cada Pod, então ao invés de criarmos um volume diferente, criamos um tamplate que será utilizado para criar um volume para cada Pod.
  - metadata:
      name: www  # Nome do volume, assim teremos o volume www-0. wwww-1 e www-2
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
