apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  imutable: true  # Torna o ConfigMap imutável
data:
  nginx.conf: |
    events { }

    http {
      server {
        listen 80;
        listen 443;
        
        ssl_certificate /etc/nginx/tls/certificado.crt;
        ssl_certificate_key /etc/nginx/tls/chave-privada.key;

        location / {
          return 200 'Olá terraqueos e extreterrestres!\n';
          add_header Content-Type text/plain;
        }
      }
    }
