apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  containers:
  - name: nginx
    image: nginx
    ports:
      - containerPort: 80
      - containerPort: 443
    volumeMounts:
      - name: nginx-config-volume  # Nome do volume que vamos usar para montar o arquivo de configuração do Nginx.
        mountPath: /etc/nginx/nginx.conf  # Caminho onde o arquivo de configuração do Nginx vai ser montado 
        subPath: nginx.conf  # Nome do arquivo de configuração do Nginx.
      - name: nginx-tls  # Nome do Volume que vamos utilizar para montar o arquivo de configuração e a chave privada.
        mountPath: /etc/nginx/tls  # Caminho onde o certificado TLS e a chave privada vão ser montados.
  volumes:  # Lista de volumes que vamos usar no Pod
  - name: nginx-config-volume  # Nome do volume que vamos usar para montar o arquivo de configuração do Nignx.
    configMap:  # Tipo do volume que vamos usar
      name: nginx-config  #Nome do volume que vamos usar para montar o certificado TLS e a chave privada.
  - name: nginx-tls  # Nome do volume que vamos usar para montar o certificado TLS e a chave privada.
    secret:  # Tipo do volume que vamos usar.
      secretName: meu-servico-web-tls-secret  # Nome do Secret que vamos usar.
      items:  # Lista de arquivos que vamos montar pois dentro da secret temos dois arquivos, o certificado TLS e a chave privada
      - key: tls.crt  # Nome do arquivo que vamos montar o nome está no campo data do Secret.
        path: certificado.crt # Nome do arquivo que vai ser montado, nome que vai ser usado no campo 'ssl_certificate' do arquivo de configuração do Nginx. 
      - key: tls.key  # Nome do arquivo que vamos montar o nome está no campo data do Secret.
        path: chave-privada.key  # Nome do arquivo que vai ser montado, nome que vai ser usado no campo 'ssl_certificate_key' do arquivo de configuração do Nginx.
