apiVersion: v1
kind: Pod
metadata:
  name: giropops-pod
spec:
  containers:
  - name: giropops-container
    image: nginx
    env:  # Inicio da definição das variáveis de ambiente
    - name: USERNAME  # Nome da variável de ambiente que será usada no Pod
      valueFrom:  # Definição de onde o valor da variável de ambiente será buscado
        secretKeyRef:  # Definição da referencia de valor da variável de ambiente que será buscado em um Secret, através de uma chave
          name: giropops-secret # Nome do Secret que contém o valor da variável de ambiente que será usada no Pod
          key: username  # Nome da chave do campo do Secret que contém o valor da variável de ambiente que será usada no Pod
    - name: PASSWORD  # Nome da variável de ambiente que será usada no Pod
      valueFrom:  # Definição de onde o valor da variável de ambiente será buscado
        secretKeyRef:  # Definição da referencia de valor da variável de ambiente que será buscado em um Secret, através de uma chave
          name: giropops-secret # Nome do Secret que contém o valor da variável de ambiente que será usada no Pod
          key: password  # Nome da chave do campo do Secret que contém o valor da variável de ambiente que será usada no Pod

