apiVersion: v1
kind: Pod
metadata:
  name: meu-pod
spec:
  containers:
  - name: web-app
    image: jldevops01/servidor_web:v1
  imagePullSecrets:  # Campo que define o Secrete que armazena as credenciais do Docker
  - name: docker-hub-secret  # Nome do Secret
