apiVersion: v1  # Versão da API do Kubernetes
kind: PersistentVolume  # Tipo de objeto que estamos criando, no caso um PersistentVolume
metadata:  # Informações sobre o objeto
  labels:  # 
    storage: local
  name: meu-pv  # Nome do nosso pv
spec:  # Especificações do nosso PV
  capacity:  # Capacidade do nosso PV
    storage: 1Gi  # 1 Gigabyte de armazenamento
  accessModes:  # Modos de acesso ao PV
    - ReadWriteOnce  # Mode de acesso ReadWriteOnce, ou seja o PV pode ser montado como leitura e escrita por um único nó
  persistentVolumeReclaimPolicy: Retain  # Politica de reinvidicação do PV, ou seja o PV não será excluido quando o PVC for excluido
  hostPath:  # tipo de armazenamento que vamos utilizar no caso um hostPath
    path: /mnt/data  # Caminho do hostPath, do nosso nó, onde o PV será criado
  storageClassName: giropops  # Nome da classe de armazenamento que será utilizada.
